policy_name: 'sparsedrive'
policy_type: 'e2e'
model_type: 'ego'
results_folder_path: ''
obs_type: 'ego_e2e_obs'
ego_obs_dim: None
ego_action_dim: 3

save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

config_path: 'rift/ego/b2d/adzoo/sparsedrive/configs/sparsedrive_small_b2d_stage2.py'
ckpt_path: '/home/keyuchen/Project/ckpt/sparsedrive/sparsedrive_stage2.pth'

save_result: True