policy_name: 'uniad'
policy_type: 'e2e'
model_type: 'ego'
results_folder_path: ''
obs_type: 'ego_e2e_obs'
ego_obs_dim: None
ego_action_dim: 3

save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

config_path: 'rift/ego/b2d/adzoo/uniad/configs/stage2_e2e/base_e2e_b2d.py'
ckpt_path: 'rift/ego/b2d/ckpt/uniad/uniad_base_b2d.pth'

save_result: True